In [2]:
import pandas as pd

In [3]:
import requests
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/07-21-2022.csv'
res = requests.get(url, allow_redirects=True)
with open('COVID_JHU.csv','wb') as file:
    file.write(res.content)
JHU = pd.read_csv('COVID_JHU.csv')

In [4]:
JHU

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2022-07-22 04:21:15,33.939110,67.709953,184224,7738,NaN,NaN,Afghanistan,473.238765,4.200321
1,NaN,NaN,NaN,Albania,2022-07-21 23:21:03,41.153300,20.168300,293917,3517,NaN,NaN,Albania,10213.253180,1.196596
2,NaN,NaN,NaN,Algeria,2022-07-22 04:21:15,28.033900,1.659600,266654,6875,NaN,NaN,Algeria,608.090439,2.578247
3,NaN,NaN,NaN,Andorra,2022-07-22 04:21:15,42.506300,1.521800,45326,153,NaN,NaN,Andorra,58663.042775,0.337555
4,NaN,NaN,NaN,Angola,2022-07-22 04:21:15,-11.202700,17.873900,102209,1912,NaN,NaN,Angola,310.984502,1.870677
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4007,NaN,NaN,NaN,West Bank and Gaza,2022-07-22 04:21:15,31.952200,35.233200,672039,5664,NaN,NaN,West Bank and Gaza,13173.577689,0.842808
4008,NaN,NaN,NaN,Winter Olympics 2022,2022-07-22 04:21:15,39.904200,116.407400,535,0,NaN,NaN,Winter Olympics 2022,NaN,0.000000
4009,NaN,NaN,NaN,Yemen,2022-07-22 04:21:15,15.552727,48.516388,11849,2149,NaN,NaN,Yemen,39.727126,18.136552
4010,NaN,NaN,NaN,Zambia,2022-07-22 04:21:15,-13.133897,27.849332,328550,4013,NaN,NaN,Zambia,1787.156149,1.221427
4011,NaN,NaN,NaN,Zimbabwe,2022-07-22 04:21:15,-19.015438,29.154857,256217,5570,NaN,NaN,Zimbabwe,1723.866369,2.173938