In [24]:
import pandas as pd

In [38]:
import warnings
warnings.filterwarnings('ignore')

In [39]:
players = pd.read_csv('../Datasets/PL/Players.csv')

In [40]:
players

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Playing Time,Playing Time.1,Playing Time.2,...,Expected.1,Expected.2,Expected.3,Per 90 Minutes.5,Per 90 Minutes.6,Per 90 Minutes.7,Per 90 Minutes.8,Per 90 Minutes.9,Unnamed: 32,-additional
0,Rk,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,...,npxG,xA,npxG+xA,xG,xA,xG+xA,npxG,npxG+xA,Matches,-9999
1,1,Max Aarons,eng ENG,DF,Norwich City,21,2000,34,32,2881,...,0.7,1.4,2.1,0.02,0.04,0.07,0.02,0.07,Matches,774cf58b
2,2,Che Adams,sct SCO,FW,Southampton,25,1996,30,23,2039,...,7.1,2.6,9.7,0.31,0.12,0.43,0.31,0.43,Matches,f2bf1b0f
3,3,Rayan Aït Nouri,fr FRA,DF,Wolves,20,2001,23,20,1828,...,0.7,1.3,2.1,0.04,0.07,0.10,0.04,0.10,Matches,9b398aea
4,4,Kristoffer Ajer,no NOR,DF,Brentford,23,1998,24,23,1995,...,0.8,1.4,2.2,0.04,0.06,0.10,0.04,0.10,Matches,a8c0acb7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
542,542,Christoph Zimmermann,de GER,DF,Norwich City,28,1993,3,2,157,...,0.1,0.0,0.1,0.04,0.00,0.04,0.04,0.04,Matches,2d5f03bf
543,543,Oleksandr Zinchenko,ua UKR,DF,Manchester City,24,1996,15,10,1047,...,0.4,2.0,2.5,0.04,0.18,0.21,0.04,0.21,Matches,51cf8561
544,544,Hakim Ziyech,ma MAR,FWMF,Chelsea,28,1993,23,14,1319,...,3.4,3.5,6.9,0.23,0.24,0.47,0.23,0.47,Matches,6622454d
545,545,Kurt Zouma,fr FRA,DF,West Ham,26,1994,24,24,2078,...,0.9,0.0,0.9,0.04,0.00,0.04,0.04,0.04,Matches,ce4246f5
546,546,Martin Ødegaard,no NOR,MF,Arsenal,22,1998,36,32,2785,...,4.8,6.8,11.6,0.16,0.22,0.38,0.16,0.38,Matches,79300479

In [41]:
players.iloc[0].values

array(['Rk', 'Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born', 'MP',
       'Starts', 'Min', '90s', 'Gls', 'Ast', 'G-PK', 'PK', 'PKatt',
       'CrdY', 'CrdR', 'Gls', 'Ast', 'G+A', 'G-PK', 'G+A-PK', 'xG',
       'npxG', 'xA', 'npxG+xA', 'xG', 'xA', 'xG+xA', 'npxG', 'npxG+xA',
       'Matches', '-9999'], dtype=object)

In [42]:
players.columns = players.iloc[0].values

In [43]:
players

,Rk,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,...,npxG,xA,npxG+xA,xG,xA,xG+xA,npxG,npxG+xA,Matches,-9999
0,Rk,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,...,npxG,xA,npxG+xA,xG,xA,xG+xA,npxG,npxG+xA,Matches,-9999
1,1,Max Aarons,eng ENG,DF,Norwich City,21,2000,34,32,2881,...,0.7,1.4,2.1,0.02,0.04,0.07,0.02,0.07,Matches,774cf58b
2,2,Che Adams,sct SCO,FW,Southampton,25,1996,30,23,2039,...,7.1,2.6,9.7,0.31,0.12,0.43,0.31,0.43,Matches,f2bf1b0f
3,3,Rayan Aït Nouri,fr FRA,DF,Wolves,20,2001,23,20,1828,...,0.7,1.3,2.1,0.04,0.07,0.10,0.04,0.10,Matches,9b398aea
4,4,Kristoffer Ajer,no NOR,DF,Brentford,23,1998,24,23,1995,...,0.8,1.4,2.2,0.04,0.06,0.10,0.04,0.10,Matches,a8c0acb7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
542,542,Christoph Zimmermann,de GER,DF,Norwich City,28,1993,3,2,157,...,0.1,0.0,0.1,0.04,0.00,0.04,0.04,0.04,Matches,2d5f03bf
543,543,Oleksandr Zinchenko,ua UKR,DF,Manchester City,24,1996,15,10,1047,...,0.4,2.0,2.5,0.04,0.18,0.21,0.04,0.21,Matches,51cf8561
544,544,Hakim Ziyech,ma MAR,FWMF,Chelsea,28,1993,23,14,1319,...,3.4,3.5,6.9,0.23,0.24,0.47,0.23,0.47,Matches,6622454d
545,545,Kurt Zouma,fr FRA,DF,West Ham,26,1994,24,24,2078,...,0.9,0.0,0.9,0.04,0.00,0.04,0.04,0.04,Matches,ce4246f5
546,546,Martin Ødegaard,no NOR,MF,Arsenal,22,1998,36,32,2785,...,4.8,6.8,11.6,0.16,0.22,0.38,0.16,0.38,Matches,79300479

In [44]:
players = players.iloc[1:]

In [45]:
players.index = players['Rk']

In [46]:
players.drop('Rk',axis=1,inplace=True)

In [47]:
players

,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,90s,...,npxG,xA,npxG+xA,xG,xA,xG+xA,npxG,npxG+xA,Matches,-9999
Rk,,,,,,,,,,,,,,,,,,,,,
1,Max Aarons,eng ENG,DF,Norwich City,21,2000,34,32,2881,32.0,...,0.7,1.4,2.1,0.02,0.04,0.07,0.02,0.07,Matches,774cf58b
2,Che Adams,sct SCO,FW,Southampton,25,1996,30,23,2039,22.7,...,7.1,2.6,9.7,0.31,0.12,0.43,0.31,0.43,Matches,f2bf1b0f
3,Rayan Aït Nouri,fr FRA,DF,Wolves,20,2001,23,20,1828,20.3,...,0.7,1.3,2.1,0.04,0.07,0.10,0.04,0.10,Matches,9b398aea
4,Kristoffer Ajer,no NOR,DF,Brentford,23,1998,24,23,1995,22.2,...,0.8,1.4,2.2,0.04,0.06,0.10,0.04,0.10,Matches,a8c0acb7
5,Nathan Aké,nl NED,DF,Manchester City,26,1995,14,10,923,10.3,...,1.1,0.5,1.6,0.11,0.05,0.16,0.11,0.16,Matches,eaeca114
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
542,Christoph Zimmermann,de GER,DF,Norwich City,28,1993,3,2,157,1.7,...,0.1,0.0,0.1,0.04,0.00,0.04,0.04,0.04,Matches,2d5f03bf
543,Oleksandr Zinchenko,ua UKR,DF,Manchester City,24,1996,15,10,1047,11.6,...,0.4,2.0,2.5,0.04,0.18,0.21,0.04,0.21,Matches,51cf8561
544,Hakim Ziyech,ma MAR,FWMF,Chelsea,28,1993,23,14,1319,14.7,...,3.4,3.5,6.9,0.23,0.24,0.47,0.23,0.47,Matches,6622454d
545,Kurt Zouma,fr FRA,DF,West Ham,26,1994,24,24,2078,23.1,...,0.9,0.0,0.9,0.04,0.00,0.04,0.04,0.04,Matches,ce4246f5
546,Martin Ødegaard,no NOR,MF,Arsenal,22,1998,36,32,2785,30.9,...,4.8,6.8,11.6,0.16,0.22,0.38,0.16,0.38,Matches,79300479

In [52]:
players.iloc[:,-2:]

     Matches     -9999
Rk
1    Matches  774cf58b
2    Matches  f2bf1b0f
3    Matches  9b398aea
4    Matches  a8c0acb7
5    Matches  eaeca114
..       ...       ...
542  Matches  2d5f03bf
543  Matches  51cf8561
544  Matches  6622454d
545  Matches  ce4246f5
546  Matches  79300479

[546 rows x 2 columns]

In [53]:
players.drop(players.iloc[:,-2:], axis=1, inplace=True)

In [54]:
players

,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,90s,...,G+A-PK,xG,npxG,xA,npxG+xA,xG,xA,xG+xA,npxG,npxG+xA
Rk,,,,,,,,,,,,,,,,,,,,,
1,Max Aarons,eng ENG,DF,Norwich City,21,2000,34,32,2881,32.0,...,0.06,0.7,0.7,1.4,2.1,0.02,0.04,0.07,0.02,0.07
2,Che Adams,sct SCO,FW,Southampton,25,1996,30,23,2039,22.7,...,0.44,7.1,7.1,2.6,9.7,0.31,0.12,0.43,0.31,0.43
3,Rayan Aït Nouri,fr FRA,DF,Wolves,20,2001,23,20,1828,20.3,...,0.15,0.7,0.7,1.3,2.1,0.04,0.07,0.10,0.04,0.10
4,Kristoffer Ajer,no NOR,DF,Brentford,23,1998,24,23,1995,22.2,...,0.18,0.8,0.8,1.4,2.2,0.04,0.06,0.10,0.04,0.10
5,Nathan Aké,nl NED,DF,Manchester City,26,1995,14,10,923,10.3,...,0.20,1.1,1.1,0.5,1.6,0.11,0.05,0.16,0.11,0.16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
542,Christoph Zimmermann,de GER,DF,Norwich City,28,1993,3,2,157,1.7,...,0.00,0.1,0.1,0.0,0.1,0.04,0.00,0.04,0.04,0.04
543,Oleksandr Zinchenko,ua UKR,DF,Manchester City,24,1996,15,10,1047,11.6,...,0.34,0.4,0.4,2.0,2.5,0.04,0.18,0.21,0.04,0.21
544,Hakim Ziyech,ma MAR,FWMF,Chelsea,28,1993,23,14,1319,14.7,...,0.48,3.4,3.4,3.5,6.9,0.23,0.24,0.47,0.23,0.47
545,Kurt Zouma,fr FRA,DF,West Ham,26,1994,24,24,2078,23.1,...,0.04,0.9,0.9,0.0,0.9,0.04,0.00,0.04,0.04,0.04
546,Martin Ødegaard,no NOR,MF,Arsenal,22,1998,36,32,2785,30.9,...,0.36,4.8,4.8,6.8,11.6,0.16,0.22,0.38,0.16,0.38

In [57]:
players.Nation.unique()

array(['eng ENG', 'sct SCO', 'fr FRA', 'no NOR', 'nl NED', 'es ESP',
       'br BRA', 'py PAR', 'co COL', 'gh GHA', 'dk DEN', 'jm JAM',
       'ga GAB', 'at AUT', 'ci CIV', 'gd GRN', 'pl POL', 'ba BIH',
       'dz ALG', 'uy URU', 'be BEL', 'is ISL', 'ml MLI', 'al ALB',
       'ar ARG', 'ec ECU', 'wls WAL', 'pt POR', 'nir NIR', 'ie IRL',
       'ao ANG', 'cz CZE', 'zm ZAM', 'ng NGA', 'sk SVK', 'se SWE',
       'eg EGY', 'fi FIN', 'ir IRN', 'gr GRE', 'de GER', 'kr KOR',
       'mx MEX', 'it ITA', 'tr TUR', 'cd COD', 'gn GUI', 'sn SEN',
       'hr CRO', 'ma MAR', 'rs SRB', 'cm CMR', 'tn TUN', 'jp JPN',
       'ua UKR', 'zw ZIM', 'us USA', 'xk KVX', 've VEN', 'ch SUI',
       'cl CHI', 'bf BFA', 'nz NZL'], dtype=object)

In [98]:
idxs = players.Nation.str.index(' ')

In [116]:
players.Nation[0][4:]

'ENG'

In [104]:
idxs

Rk
1      3
2      3
3      2
4      2
5      2
      ..
542    2
543    2
544    2
545    2
546    2
Name: Nation, Length: 546, dtype: int64

In [107]:
len(idxs)

546

In [122]:
i=0
r=[]
while i<len(idxs):
    r.append(players.Nation[i][idxs[i]+1:])
    i+=1

In [123]:
r

['ENG',
 'SCO',
 'FRA',
 'NOR',
 'NED',
 'ENG',
 'ESP',
 'ENG',
 'BRA',
 'BRA',
 'ENG',
 'ENG',
 'PAR',
 'ESP',
 'COL',
 'GHA',
 'DEN',
 'JAM',
 'ENG',
 'FRA',
 'ENG',
 'SCO',
 'ESP',
 'SCO',
 'GAB',
 'GHA',
 'ENG',
 'ESP',
 'AUT',
 'JAM',
 'CIV',
 'ENG',
 'ENG',
 'GRN',
 'ENG',
 'ENG',
 'ENG',
 'ENG',
 'DEN',
 'POL',
 'NED',
 'NED',
 'BIH',
 'ALG',
 'URU',
 'BEL',
 'ISL',
 'NED',
 'ENG',
 'DEN',
 'MLI',
 'CIV',
 'ENG',
 'ENG',
 'ALB',
 'ENG',
 'ENG',
 'ESP',
 'ARG',
 'ENG',
 'ENG',
 'ENG',
 'ENG',
 'ARG',
 'ECU',
 'ENG',
 'WAL',
 'POR',
 'ESP',
 'ENG',
 'POL',
 'BEL',
 'ESP',
 'NIR',
 'URU',
 'BRA',
 'ENG',
 'ENG',
 'ENG',
 'ENG',
 'ENG',
 'POR',
 'ENG',
 'DEN',
 'ENG',
 'IRL',
 'ENG',
 'ENG',
 'ENG',
 'IRL',
 'IRL',
 'IRL',
 'SCO',
 'ENG',
 'CIV',
 'ANG',
 'CZE',
 'BRA',
 'ENG',
 'ENG',
 'COL',
 'ESP',
 'ENG',
 'ZAM',
 'NIR',
 'POR',
 'ENG',
 'ENG',
 'WAL',
 'ENG',
 'ENG',
 'ENG',
 'BEL',
 'ENG',
 'ENG',
 'ENG',
 'BEL',
 'NGA',
 'ENG',
 'FRA',
 'POR',
 'COL',
 'ENG',
 'FRA',
 'FRA',
 'FRA',
 'MLI',
 'ENG',
 'IRL',
 'BRA',
 'MLI',
 'ENG',
 'ENG',
 'SVK',
 'IRL',
 'WAL',
 'ENG',
 'BRA',
 'FRA',
 'ENG',
 'SWE',
 'ENG',
 'EGY',
 'NOR',
 'BRA',
 'DEN',
 'NGA',
 'NIR',
 'ENG',
 'POL',
 'BRA',
 'ESP',
 'IRL',
 'ENG',
 'POR',
 'ESP',
 'ARG',
 'BRA',
 'BRA',
 'ESP',
 'ENG',
 'ENG',
 'FRA',
 'ESP',
 'ENG',
 'FIN',
 'ENG',
 'ENG',
 'GHA',
 'SCO',
 'BRA',
 'ENG',
 'NOR',
 'ENG',
 'ESP',
 'ENG',
 'CIV',
 'ESP',
 'ENG',
 'NED',
 'NED',
 'IRN',
 'GRE',
 'ENG',
 'ENG',
 'SCO',
 'ENG',
 'POR',
 'POR',
 'ENG',
 'ENG',
 'ENG',
 'ENG',
 'ENG',
 'ENG',
 'ENG',
 'ENG',
 'ENG',
 'GER',
 'ESP',
 'ENG',
 'BRA',
 'GER',
 'ENG',
 'SCO',
 'ENG',
 'ENG',
 'GER',
 'ENG',
 'KOR',
 'ENG',
 'IRL',
 'WAL',
 'ENG',
 'KOR',
 'NED',
 'ENG',
 'ENG',
 'ENG',
 'ENG',
 'DEN',
 'IRL',
 'NGA',
 'ENG',
 'ENG',
 'NGA',
 'WAL',
 'WAL',
 'ENG',
 'GER',
 'SWE',
 'DEN',
 'BRA',
 'MEX',
 'BRA',
 'BRA',
 'ENG',
 'ENG',
 'ENG',
 'ITA',
 'POR',
 'ENG',
 'DEN',
 'TUR',
 'BEL',
 'NGA',
 'CIV',
 'ENG',
 'FRA',
 'COD',
 'ITA',
 'ENG',
 'GUI',
 'IRL',
 'BRA',
 'ENG',
 'ENG',
 'NOR',
 'NOR',
 'POL',
 'GER',
 'BIH',
 'FRA',
 'ENG',
 'SEN',
 'CRO',
 'SWE',
 'CZE',
 'NED',
 'SVK',
 'SWE',
 'FRA',
 'ENG',
 'ENG',
 'ARG',
 'ESP',
 'ENG',
 'FRA',
 'ENG',
 'GER',
 'NIR',
 'SWE',
 'ENG',
 'ENG',
 'ESP',
 'FRA',
 'ARG',
 'NED',
 'ENG',
 'IRL',
 'IRL',
 'ENG',
 'NGA',
 'DEN',
 'MAR',
 'ENG',
 'BRA',
 'BEL',
 'BRA',
 'ARG',
 'ENG',
 'ENG',
 'ALG',
 'ENG',
 'SEN',
 'ESP',
 'BRA',
 'ENG',
 'ESP',
 'FRA',
 'BRA',
 'ARG',
 'MAR',
 'COD',
 'ESP',
 'FRA',
 'SRB',
 'CMR',
 'FRA',
 'FRA',
 'SCO',
 'ENG',
 'ENG',
 'SCO',
 'ENG',
 'SCO',
 'SCO',
 'SCO',
 'ENG',
 'SCO',
 'ENG',
 'TUN',
 'FRA',
 'SEN',
 'SEN',
 'FRA',
 'SRB',
 'ENG',
 'COL',
 'JPN',
 'ENG',
 'ENG',
 'POL',
 'BRA',
 'ENG',
 'ENG',
 'BRA',
 'POR',
 'ENG',
 'ENG',
 'ZAM',
 'UKR',
 'ZIM',
 'NGA',
 'FRA',
 'ENG',
 'POR',
 'POR',
 'ENG',
 'ESP',
 'ENG',
 'CMR',
 'ENG',
 'NOR',
 'DEN',
 'ITA',
 'FRA',
 'SWE',
 'IRL',
 'ENG',
 'NGA',
 'BEL',
 'ENG',
 'ENG',
 'ITA',
 'GHA',
 'CIV',
 'POR',
 'ESP',
 'ENG',
 'FRA',
 'ENG',
 'ENG',
 'ENG',
 'NED',
 'JAM',
 'POR',
 'FRA',
 'ENG',
 'NIR',
 'FIN',
 'USA',
 'POL',
 'ENG',
 'ENG',
 'ENG',
 'BRA',
 'ENG',
 'KVX',
 'ESP',
 'ENG',
 'ESP',
 'ENG',
 'ENG',
 'BRA',
 'NED',
 'SCO',
 'WAL',
 'WAL',
 'SCO',
 'WAL',
 'ESP',
 'ESP',
 'ENG',
 'DEN',
 'ARG',
 'ESP',
 'POR',
 'VEN',
 'ENG',
 'ENG',
 'ENG',
 'GER',
 'GER',
 'POR',
 'FRA',
 'MAR',
 'ENG',
 'EGY',
 'GHA',
 'BEL',
 'COL',
 'ESP',
 'ENG',
 'FRA',
 'BRA',
 'USA',
 'ECU',
 'SEN',
 'FRA',
 'ENG',
 'SUI',
 'GHA',
 'DEN',
 'SWE',
 'POR',
 'ENG',
 'ENG',
 'ENG',
 'ENG',
 'ENG',
 'CHI',
 'POR',
 'POR',
 'BRA',
 'ENG',
 'FRA',
 'ENG',
 'IRL',
 'ENG',
 'POR',
 'CZE',
 'FRA',
 'TUR',
 'ENG',
 'ENG',
 'ENG',
 'USA',
 'ENG',
 'ENG',
 'ENG',
 'WAL',
 'ENG',
 'NED',
 'NED',
 'DEN',
 'ENG',
 'ENG',
 'ENG',
 'ENG',
 'POR',
 'ENG',
 'ENG',
 'BRA',
 'ENG',
 'ENG',
 'BEL',
 'SCO',
 'JPN',
 'ENG',
 'ENG',
 'ESP',
 'TUR',
 'ENG',
 'ESP',
 'BFA',
 'EGY',
 'POR',
 'ENG',
 'NGA',
 'BEL',
 'GRE',
 'ENG',
 'TUR',
 'GRE',
 'FRA',
 'NED',
 'FRA',
 'ENG',
 'NED',
 'DEN',
 'CRO',
 'CZE',
 'ENG',
 'ENG',
 'ENG',
 'ENG',
 'WAL',
 'ENG',
 'ENG',
 'ENG',
 'ENG',
 'NED',
 'ENG',
 'GER',
 'ENG',
 'ENG',
 'ENG',
 'WAL',
 'ENG',
 'ENG',
 'ENG',
 'COD',
 'NZL',
 'NZL',
 'ENG',
 'SUI',
 'UKR',
 'ENG',
 'ENG',
 'CIV',
 'GER',
 'UKR',
 'MAR',
 'FRA',
 'NOR']

In [124]:
players.Nation = r

In [125]:
players

,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,90s,...,G+A-PK,xG,npxG,xA,npxG+xA,xG,xA,xG+xA,npxG,npxG+xA
Rk,,,,,,,,,,,,,,,,,,,,,
1,Max Aarons,ENG,DF,Norwich City,21,2000,34,32,2881,32.0,...,0.06,0.7,0.7,1.4,2.1,0.02,0.04,0.07,0.02,0.07
2,Che Adams,SCO,FW,Southampton,25,1996,30,23,2039,22.7,...,0.44,7.1,7.1,2.6,9.7,0.31,0.12,0.43,0.31,0.43
3,Rayan Aït Nouri,FRA,DF,Wolves,20,2001,23,20,1828,20.3,...,0.15,0.7,0.7,1.3,2.1,0.04,0.07,0.10,0.04,0.10
4,Kristoffer Ajer,NOR,DF,Brentford,23,1998,24,23,1995,22.2,...,0.18,0.8,0.8,1.4,2.2,0.04,0.06,0.10,0.04,0.10
5,Nathan Aké,NED,DF,Manchester City,26,1995,14,10,923,10.3,...,0.20,1.1,1.1,0.5,1.6,0.11,0.05,0.16,0.11,0.16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
542,Christoph Zimmermann,GER,DF,Norwich City,28,1993,3,2,157,1.7,...,0.00,0.1,0.1,0.0,0.1,0.04,0.00,0.04,0.04,0.04
543,Oleksandr Zinchenko,UKR,DF,Manchester City,24,1996,15,10,1047,11.6,...,0.34,0.4,0.4,2.0,2.5,0.04,0.18,0.21,0.04,0.21
544,Hakim Ziyech,MAR,FWMF,Chelsea,28,1993,23,14,1319,14.7,...,0.48,3.4,3.4,3.5,6.9,0.23,0.24,0.47,0.23,0.47
545,Kurt Zouma,FRA,DF,West Ham,26,1994,24,24,2078,23.1,...,0.04,0.9,0.9,0.0,0.9,0.04,0.00,0.04,0.04,0.04
546,Martin Ødegaard,NOR,MF,Arsenal,22,1998,36,32,2785,30.9,...,0.36,4.8,4.8,6.8,11.6,0.16,0.22,0.38,0.16,0.38